### ISSUE TITLE
user view of orders/accounts information

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#16]
a user view of orders and account information, linked in their account dropdown.

**Comment by aaronjudd** [comment]
https://github.com/reactioncommerce/reaction-core/commit/5bf1d873c8dde6b76a93a36f342051b998a8e805 adds `provides='userAccountDropdown'` to `reactionApp` dynamicTemplates.

**Comment by aaronjudd** [comment]
Initial implementation resolved by https://github.com/reactioncommerce/reaction-core/pull/111

**Comment by Gouthamve** [comment]
I am still not seeing anything in the user dropdown.
![screen shot 2015-03-16 at 11 26 20 am](https://cloud.githubusercontent.com/assets/7354143/6661251/6cbce4e8-cbcf-11e4-9e73-4439ce7f3889.png)

**Comment by aaronjudd** [comment]
![screenshot 2015-03-15 23 58 39](https://cloud.githubusercontent.com/assets/439959/6661773/42378bca-cb6f-11e4-8fe7-5d44b4920a9f.png)
