### ISSUE TITLE
i18n language switching bug

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#235]
I found issue with current i18n implementation.
I select spanish language on the product page of unvisible product -> string became spanish. 
I make product visible and half-translated message "Gestión de productos Make invisible | Delete" appear.
If I select spanish language again message becames "Gestión de productos Hacer invisible | Delete", which means some translations defined, but not applied using current language from session.

![screen](http://i.imgur.com/15sccpB.png)

![screen](http://i.imgur.com/zKsUBng.png)
Do you have an idea what the reason of this? Does application use any exising i18n package?

**Comment by lovetostrike** [comment]
This doesn't happen in v0.2.2 and a different behavior(which I think is a bug as well) appears. I would file a bug report for v0.2.2.

**Comment by aaronjudd** [comment]
@ramusus is this addressed in https://github.com/reactioncommerce/reaction-core/pull/65  ?

**Comment by ramusus** [comment]
No, there are just some translations, bug is still here

**Comment by ramusus** [comment]
I just installed 0.2.2 and this bug still there. @lovetostrike what behaviour appears for you?

**Comment by aaronjudd** [comment]
I think this is just that some translations aren't defined.
We always fall back to  english in translations, or - fall back to template text if it's not defined in the translations.  Most likely I just missed some of the translations (particular for the "alert" messages).

The i18n system is a custom reactive implementation of i18next.js

@ramusus v0.2.2 doesn't have the changes you made in your pull requests to master, but I tested in v0.2.2 and it seemed to work fine

**Comment by ramusus** [comment]
@aaronjudd I didn't make a PR for solving this issue. https://github.com/reactioncommerce/reaction-core/pull/65 is just new translation containers and phrases.

I uploaded video with bug I see http://youtu.be/YWrXTsH20zE. I guess problem is not missing of translations, but is non-reactive nature of some parts of code.

**Comment by ramusus** [comment]
I checked in chrome source debugger when switching product visibility event Template.onRendered is not called. My version of meteor is Meteor 1.0.2.1

**Comment by aaronjudd** [comment]
@ramusus this is a little ugly, probably needs some more thought, but basically the dependency wasn't re-triggered when a template was already rendered (the messages) and then re-rendered. I've added a method to rerun i18n in this case, but it's a little kludge in the way it renders (but works).

**Comment by ramusus** [comment]
thanks @aaronjudd! I checked it. English language flush for a short moment before, but it shows right language finally.

**Comment by ramusus** [comment]
I checked this in development branch and bug is here again
