### ISSUE TITLE
[Marketplace] Clicking on result in Account/Order search does nothing

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2625]
### Expected behavior
Clicking on result should take you to the "Manage Account" screen, or Order management screen

### Actual Behavior
Nothing happens

### Steps to Reproduce the Behavior
1. Login as admin
1. Search for an account or order
1. Click on result
1. Observe nothing happens

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
commit: b6e18a4b5a35b852bd75648ae395a2f4b77eae81
```

**Comment by rymorgan** [comment]
If the search results end on a user that is not an admin, we should link to their user profile page. (in the future this should/will include their order history and user analytics. But for now, it can just be the current user profile page.)

**Comment by zenweasel** [comment]
This should be solved with #2834 as well so I am assigning to @foladipo

**Comment by foladipo** [comment]
Seen @zenweasel . And yeah, #2834 should resolve this.

**Comment by joykare** [comment]
@foladipo I see this is still on the PR list 
Wanna take a look at it together?

**Comment by foladipo** [comment]
Yeah, no problem. But we'll have to commit our work to #2834 . The major part remaining in that PR is that the search form gets 'stuck' some times. See the PR's conversation for details.

**Comment by foladipo** [comment]
@joykare This issue has been resolved already in #2834. I'm going to close it now.

**Comment by zenweasel** [comment]
Let's not close tickets until PR's are merged please

**Comment by joykare** [comment]
Its not resolved its just on the PR list. We'll close when your PR gets merged @foladipo

**Comment by joykare** [comment]
@foladipo I made some changes that should fix the getting stuck issue.
Could you test it out

**Comment by spencern** [comment]
Resolved by #2834

**Comment by foladipo** [comment]
Roger that @zenweasel and @joykare .
