### ISSUE TITLE
Development version of React in production

### ISSUE THREAD

**Issue by callmephilip** [reactioncommerce/reaction#2629]
I am checking https://hello.reactioncommerce.com/ with [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) and it says that the site is using development version of React. Does this deployment do it intentionally or is this a bug?

**Comment by aaronjudd** [comment]
This should have been resolved with the release of Meteor 1.5.1 https://blog.meteor.com/announcing-meteor-1-5-1-b65ecddf955b

we're using https://github.com/abernix/standard-minifier-js 2.1.0 instead of https://github.com/meteor/meteor/tree/devel/packages/standard-minifier-js 2.1.1

The abernix package apparently hasn't yet been updated since the release of 2.1.1.

**Comment by zenweasel** [comment]
I still see this issue on https://swag.getreaction.io using RC 1.5.11. Checking a couple of the sites on the community showcase they appear to also using the development version of React.

**Comment by zenweasel** [comment]
Since this affects sites in production I am tempted to bump this bug up to critical. Any input @aaronjudd?

**Comment by zenweasel** [comment]
Spoke to @aaronjudd this morning and we agreed that this needs to be bumped up to critical and we need to resolve it **now**.

**Comment by jshimko** [comment]
Switched back to `standard-minifier-js` and that fixed it.  Just did a Docker build of master with `standard-minifier-js` added and the `abernix` fork removed and it is now properly compiling React.

**Comment by zenweasel** [comment]
Now the mystery is, why did we switch in the first place and is it safe to switch back? 🤔

**Comment by zenweasel** [comment]
Closed via #3363
