### ISSUE TITLE
A way to archive and disable a shop

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#2864]
As the marketplace owner, I should have the ability to: 
1. Archive or disable a shop - which includes removing permissions/access for all users of that shop
2. Archive or un-publish all of the products from that shop (make it invisible) 
3. Remove that shop from the navigation

**Comment by aaronjudd** [comment]
This is a duplicate, extension, or just a more focused version of https://github.com/reactioncommerce/reaction/issues/1578 -> but that's important to understanding this issue.

**Comment by aaronjudd** [comment]
@spencern we should have an architectural discussion about this. I'd suggest that we should use a `workflow` status, to accomodate: 'archived', 'visibility', and other possible publishing states for a shop at a global level.  We can add to the various publications (products) for filtering/validation of these, and also using permissions.

**Comment by spencern** [comment]
@aaronjudd 
I agree that we should have various states for shops. We've discussed the desire to have visibility and publication status both be more flexible than booleans on Products and I don't see any reason not to work with that mindset for Shops as well.

Here are some initial thoughts I've got on a shops workflow

**Shop Workflow**
This may be different for merchant shops than for primary shops.
I see this as the approval and publication workflow for a "managed" merchant shop. My initial thoughts would have the workflow looking something like this:
**Shop Workflow**
  * **Pending** - a shop that has been created for a user, but the user hasn't accepted managing that shop is in this state
  * **New** - if users can create a shop without an invite, they start here, otherwise when they have accepted their invite, their shop is set to this state.
  * **Valid** - All essential information has been filled out and is in good standing (address, payment info, tax info, shipping rates, etc - anything that is required to be submitted has been submitted)
  * **Invalid** - Could be shared with "new" but might be good to have a way to distinguish shops that are in an invalid state because of neglect, vs those that haven't been set up yet.
  * **Active** - Shop is in a valid state and has been approved/enabled/published by the marketplace owner if there is a an approval queue
  * **Archived** - May need sub status or "reason" that could determine whether the user can re-open or if the marketplace must re-open - e.g. Closed, Paused, Banned, Suspended, 

A few questions:
1. Is there a need to have a visibility property in addition to these workflows? Should it be a part of the workflow or separate.
2. Are there use cases that are not covered by any of these workflows? Do we need an "inactive" status?
3. Some of these states are meant to be moved between while others are steps in a process, is there any good reason to separate those concepts?

I agree that there's a need to have some type of publishing workflow for products to the marketplace that might be similar.

**Comment by mikemurray** [comment]
Between this ticket and #1578, what's required to get this rolling as an initial start?

**Comment by spencern** [comment]
MVP thoughts:

I feel that we should still use the workflow/status to determine which shops are active and which shops are not, this will make the transition from simple -> complex shop management much simpler and make the upgrade path possible.

I think we could start with just using two statuses to determine enabled/disable -> "Active" and "Archived" - for now perhaps "Archived" is just an indicator that the shop is disable and it's products should not appear in the product grid, and that the shop should not appear in the navigation. (side note: Mike, we may need to add `status` to the `merchantShops` array)

I think a simple list/table of shops (similar to how we list admin accounts) within a "shops" dashboard should be good enough as an MVP as well. The table could have the shop name, email contact, and a dropdown to select enabled/disabled (corresponding to "active" and "archived")

@mikemurray @aaronjudd any thoughts on this?

**Comment by mikemurray** [comment]
@spencern That's a simple enough concept to start with.

Maybe not for now, but should have some extra metadata stating the reason or at least a date of when a shop became active, archived or other status changes.

**Comment by kieckhafer** [comment]
Is "archived" the best terminology? I think `disabled` works better for a store.

**Comment by spencern** [comment]
@kieckhafer I don't disagree with that idea in premise. Do you think we should add an additional status in the workflow seen above? I feel like archived probably still has a place in the workflow as it's our version of "deleted", but agree that semantically, enabled/disabled might make more sense immediately.

How would you describe the differences between `disabled` and `archived`?

The reason I proposed `active` and `archived` for now is that the statuses I proposed earlier do not have a `disabled` status and I don't think we should create a new status for the short term solution.

I have thought about this, but I'd welcome some debate on the semantics and specific statuses that we should use.

**Comment by kieckhafer** [comment]
Yeah i see why it's proposed this way, archived does go with our currently terminology. It could just be on the UI end, we change it to say "Disabled" instead of archived, but architecturally, we still keep it archived. I don't think we need an additional status, I see archived and disabled as the same.

> How would you describe the differences between disabled and archived?

It's hard to pinpoint. I guess I think of using `Archived` for a single item that doesn't really affect anything else, and something that you may want to access semi-frequently, even in it's archived state. More of a "get this off my screen, but keep it around because I might want it soon".

I think the word disabled, in this sense, holds more power. Archive is just a "Meh, archive it, we can come back to it"... Disabled is like "are you sure you want to turn this whole shop off?"


> How would you describe the differences between disabled and archived?

I feel like archived is for a single standalone item - and you could argue that the shop as a whole is a single standalone item as well, but

**Comment by mikemurray** [comment]
Using `archived` to match with the `archived` state of all the products & content in that shop will be, once you archive that shop. It's not merely `disabled` to be maybe re-enabled. It's `archived` and most likely will never be re-instated. Deleted, but capable of being re-restored to some extent.

- Disabled is like a temporary ban. (Visible / Not Visible)
- Archived is like a permanent ban. (Essentially deleted)

**Comment by mikemurray** [comment]
And they are not necessarily exclusive. A shop could be both `disabled` and `archived`.

**Comment by rymorgan** [comment]
@mikemurray How much or how little fixing of the current accounts UI are you going to do on this issue?  Because this is going to be copying a UI from a broken UI. I can help design this out, but I'm going to design it to where I want it to be, not where it is now.

**Comment by spencern** [comment]
@mikemurray I think that explanation makes sense, I've changed the proposal I have above and use `disabled` in place of `invalid` now.

**Comment by mikemurray** [comment]
@rymorgan very little fixing if possible. I was going to start with a table view only for the start.

**Comment by spencern** [comment]
Resolved by #3049

**Comment by zenweasel** [comment]
When I disable a shop should I still see their products as an admin? They disappear for the average user for still appear for admins

**Comment by spencern** [comment]
I think that's how @mikemurray designed this first iteration.
