### ISSUE TITLE
[Marketplace] Individual shop pages show items from all shops, and without images

### ISSUE THREAD

**Issue by JoeyLyman** [reactioncommerce/reaction#2890]
### Expected behavior
I would expect the main shop page to show all items from every seller, and individual seller pages (i.e. Reaction1 created by a guest seller) to show their items only.

### Actual Behavior
As a guest seller, if I go to my shop (i.e. Reaction1 that I made as a guest) it will show all the items (the ones that I made as an Admin and the ones I made on the Guest seller account).  There is no clear indication which items are associated with my Guest account that I am currently logged in as.  Also, on the main shop page (Reaction), the images show up only on the products created by the Admin, but not the products created by guest sellers.  Furthermore, on the Reaction1 and other shops (Guest-created shops), no images show up at all, from products created from the Admin or by this guest seller.  

### Steps to Reproduce the Behavior
Create products as an admin.
Log out and create products as a guest, and try to upload images.
Look at Reaction shop page, and Reaction1 shop page.

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.12.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by aaronjudd** [comment]
Related to #2760 in progress @jshimko @mikemurray

**Comment by spencern** [comment]
@JoeyLyman This may have (I think should have) been solved by #2760 / #2929. Can you check it again? Also I think there is some overlap between this issue and #2889 

@mikemurray do you think that this is solved now?

**Comment by mikemurray** [comment]
@spencern I thought we had an issue that, as a marketplace owner, you still see all products on all grids because of the publication. Will verify shortly.

**Comment by spencern** [comment]
@mikemurray We ended up solving something related to this by attaching it to the "edit mode" switch.

**Comment by mikemurray** [comment]
@spencern the edit mode is fine for that, but I noticed some other issues while testing.

The slug for newly created shops is still "reaction" for some reason. Maybe because we duplicate the original shop.

After changing the slug in mongo to `reaction1` I still get" no products found" on `/shop/reaction1`. The product is published and visible and shows up on `/` for both admin and marketplace shop owner though.

**Comment by mikemurray** [comment]
Also not having images is a real issue. Seems marketplace owners don't have permissions to upload photos.

**Comment by spencern** [comment]
@mikemurray - I've been digging through the `shops/createShop` method while fixing #2889, so I'll see if I can figure some of this out

**Comment by spencern** [comment]
@mike I've figured out the slug creation issue issue and that will get fixed in my fix for #2889 

Haven't looked into the images issue yet.

**Comment by mikemurray** [comment]
@spencern for the media I have to believe it's something to do with the allow/deny here: https://github.com/reactioncommerce/reaction/blob/marketplace/server/security/collections.js#L128

**Comment by spencern** [comment]
@mikemurray Maybe fixed by https://github.com/reactioncommerce/reaction/pull/2918 then?

**Comment by mikemurray** [comment]
@spencern that's the ticket!

**Comment by spencern** [comment]
Working on this right now. 
The only issue remaining here is that merchant shops routes aren't displaying their products currently.
![image](https://user-images.githubusercontent.com/1203639/31151659-b674421a-a855-11e7-9ba8-609f862c5c14.png)

**Comment by spencern** [comment]
Resolved by #3022
