### ISSUE TITLE
Shop general settings update failed. Error: Verified is required

### ISSUE THREAD

**Issue by Vigyano** [reactioncommerce/reaction#374]
Administrator -> Dashboard -> Core -> Settings -> Shop -> General
--------

Following error occurs when updating general setting and if the email field is filled. If there is no email, then the update works.

```
Shop general settings update failed. Error: Verified is required
```

**Comment by aaronjudd** [comment]
Fixed in feature branch https://github.com/reactioncommerce/reaction-core/commit/6f8c546faec1ff0214f67136ba61997d0f34519f

**Comment by Vigyano** [comment]
Now I get following Access denied error. I got the ```feature-roles-372``` branch and logged in as admin. I did meteor reset to reset the project but still getting access denied. This time even removing the email field doesn't help. Am I missing any steps?

```
Shop general settings update failed. Error: Access denied [403]
```

**Comment by aaronjudd** [comment]
I'm not sure I'd recommend 372 use just yet - it's still a little rough (although it should work).  I'd suggest you do a `meteor reset` before using that branch though, as the permissions will need to be rebuilt.

You might get a few access errors (as it's a new permissions implementation) - but this particularly one I tested and fixed. 

If you want to fix in the current dev branch, make "verified" be "optional:true" in the `schemas/shops.coffee`

**Comment by Vigyano** [comment]
I switched to dev branch of core package but I don't see verified field in shops.coffee. I am looking at below script at /reacion-core/common/schemas/shops.coffee. Am I looking at right file?

https://github.com/reactioncommerce/reaction-core/blob/development/common/schemas/shops.coffee
