### ISSUE TITLE
Cannot switch orders dashboard between list and table view

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3760]
### Expected behavior

Should be able to switch between table and list view of orders dashboard.

### Actual behavior

Receive a `moment is not a function` error, and the view never switches.

![basic_reaction_product](https://user-images.githubusercontent.com/42217/36285007-d0ba2e28-125e-11e8-8d8a-6fe1983bf326.png)

![screen shot 2018-02-15 at 2 41 55 pm](https://user-images.githubusercontent.com/42217/36284978-b3ab0c76-125e-11e8-8a6c-ed16495e1176.png)

### Steps to reproduce the behavior

1. As any user, create an order by checking out with products
1. As an admin, open the order dashboard
1. In the upper right corner, there will be two icons that will allow you to toggle table and list view. (see screenshot)
1. Click the one that's not highlighted
1. In the console, observe generated errors

### Versions

Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce

**Comment by prinzdezibel** [comment]
Not repro.
 
Probably fixed with: 

`c672be50c Merge pull request #3602 from reactioncommerce/feat-2635-kieckhafer-
dynamicallyLoadMoment`

**Comment by prinzdezibel** [comment]
@mikemurray  Can you verify that? If so, I'm going to close.

**Comment by zenweasel** [comment]
I've verified that this is still happening on the current HEAD on `release-1.8.0`

**Comment by zenweasel** [comment]
Closed via #3773
