### ISSUE TITLE
startup fail 

### ISSUE THREAD

**Issue by lynnnyn** [reactioncommerce/reaction#4765]
## Issue Description
Providing a clear description of the issue will enable a developer to quickly reproduce and understand the issue. Please provide a detailed description including images, animation and/or videos. For client issues, include browser console errors, for server issues please add terminal output and stack traces.

log for reaction:
reaction_1  | npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
reaction_1  | npm WARN react-taco-table@0.5.1 requires a peer of react@^15.3 but none is installed. You must install peer dependencies yourself.
reaction_1  | npm WARN react-taco-table@0.5.1 requires a peer of react-dom@^15.3 but none is installed. You must install peer dependencies yourself.
reaction_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
reaction_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
reaction_1  | 
reaction_1  | up to date in 14.028s
reaction_1  | MongoDB replica set initialized and ready.
reaction_1  | Setting up plugin imports...
reaction_1  | 
reaction_1  | Setting up style imports...
reaction_1  | 
reaction_1  | Provisioning assets...
reaction_1  | 
reaction_1  | [[[[[ /opt/reaction/src ]]]]]
reaction_1  | 
reaction_1  | => Started proxy.
reaction_1  | => Meteor 1.8 is available. Update this project with 'meteor update'.
reaction_1  | Killed
reaction_1  | { Error: Command failed: meteor --raw-logs
reaction_1  |     at checkExecSyncError (child_process.js:601:13)
reaction_1  |     at execSync (child_process.js:641:13)
reaction_1  |     at _callee$ (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:72:43)
reaction_1  |     at tryCatch (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:65:40)
reaction_1  |     at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:303:22)
reaction_1  |     at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:117:21)
reaction_1  |     at step (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:191)
reaction_1  |     at /usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:361
reaction_1  |     at <anonymous>
reaction_1  |     at process._tickCallback (internal/process/next_tick.js:188:7)
reaction_1  |   error: null,
reaction_1  |   cmd: 'meteor --raw-logs',
reaction_1  |   file: '/bin/sh',
reaction_1  |   args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
reaction_1  |   options: 
reaction_1  |    { stdio: [ [Object], [Object], [Object] ],
reaction_1  |      shell: true,
reaction_1  |      file: '/bin/sh',
reaction_1  |      args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
reaction_1  |      envPairs: 
reaction_1  |       [ 'TOOL_NODE_FLAGS=',
reaction_1  |         'NODE_VERSION=8.11.3',
reaction_1  |         'HOSTNAME=013f57e5c4c5',
reaction_1  |         'METEOR_VERSION=1.7.0.3',
reaction_1  |         'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor',
reaction_1  |         'PWD=/opt/reaction/src',
reaction_1  |         'MONGO_URL=mongodb://mongo:27017/reaction',
reaction_1  |         'APP_BUNDLE_DIR=/opt/reaction/dist',
reaction_1  |         'ROOT_URL=http://localhost:3000',
reaction_1  |         'SHLVL=1',
reaction_1  |         'HOME=/home/node',
reaction_1  |         'YARN_VERSION=1.6.0',
reaction_1  |         'REACTION_DOCKER_BUILD=true',
reaction_1  |         'APP_SOURCE_DIR=/opt/reaction/src',
reaction_1  |         'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
reaction_1  |         'HYDRA_ADMIN_URL=http://hydra:4445',
reaction_1  |         'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
reaction_1  |         '_=/usr/local/bin/reaction' ],
reaction_1  |      killSignal: undefined },
reaction_1  |   envPairs: 
reaction_1  |    [ 'TOOL_NODE_FLAGS=',
reaction_1  |      'NODE_VERSION=8.11.3',
reaction_1  |      'HOSTNAME=013f57e5c4c5',
reaction_1  |      'METEOR_VERSION=1.7.0.3',
reaction_1  |      'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor',
reaction_1  |      'PWD=/opt/reaction/src',
reaction_1  |      'MONGO_URL=mongodb://mongo:27017/reaction',
reaction_1  |      'APP_BUNDLE_DIR=/opt/reaction/dist',
reaction_1  |      'ROOT_URL=http://localhost:3000',
reaction_1  |      'SHLVL=1',
reaction_1  |      'HOME=/home/node',
reaction_1  |      'YARN_VERSION=1.6.0',
reaction_1  |      'REACTION_DOCKER_BUILD=true',
reaction_1  |      'APP_SOURCE_DIR=/opt/reaction/src',
reaction_1  |      'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
reaction_1  |      'HYDRA_ADMIN_URL=http://hydra:4445',
reaction_1  |      'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
reaction_1  |      '_=/usr/local/bin/reaction' ],
reaction_1  |   stderr: null,
reaction_1  |   stdout: null,
reaction_1  |   pid: 76,
reaction_1  |   output: [ null, null, null ],
reaction_1  |   signal: null,
reaction_1  |   status: 137 }
reaction_1  | 
reaction_1  | Error: App failed to start
reaction_reaction_1 exited with code 1

### Versions
(run `reaction -v` from your reaction directory)
2.0.0

**Comment by spencern** [comment]
Hi @lynnnyn,

Thanks for using Reaction and taking the time to file this bug report! 

I believe that this issue is fixed in our 6th release candidate which you can try by navigating to the root `reaction` directory from your `reaction-platform` installation and checking out the `release-2.0.0-rc.6` branch.

**Comment by lynnnyn** [comment]
Hi @spencern ，
I have followed your suggestion and checkout to release-2.0.0-rc.6 branch. But it still have the same bug. 
<img width="1436" alt="screen shot 2018-10-22 at 11 24 48 am" src="https://user-images.githubusercontent.com/26138685/47306777-f7bd9980-d5f2-11e8-8a3f-c5b85e372b2d.png">

**Comment by aldeed** [comment]
@lynnnyn Also try https://docs.reactioncommerce.com/docs/troubleshooting-development#memory-errors-or-errors-about-meteor-rawlogs

**Comment by lynnnyn** [comment]
@aldeed Hi aldeel, I have followed your suggestion and it worked! Thanks!

**Comment by AaronZhangL** [comment]
I got this error.
--------------------------
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
