### ISSUE TITLE
Impossible to update options of a product or create options in a new one

### ISSUE THREAD

**Issue by tritone11** [reactioncommerce/reaction#490]
While updating the options in a product, the console throw this message:

M…r.m…e.errorClass {error: 404, reason: "Method not found", details: undefined, message: "Method not found [404]", errorType: "Meteor.Error"}
details: undefinederror: 404
errorType: "Meteor.Error"
message: "Method not found [404]"
reason: "Method not found"
stack: (...)
get stack: ()
set stack: ()
__proto__: _.extend._inherits.Middle
clone: ()
constructor: (/*arguments*/)
__proto__: DefineError.aV

The problem come also when creating a new product, it doesn't let to add options or modify the default options. In result, the product cannot be marked as "visible".
The issue occurs after a fresh install from git, without any update.

**Comment by aaronjudd** [comment]
I'll take a look, it's probably a remnant of our conversion to ES6, although tests are passing on this, which is strange.

**Comment by aaronjudd** [comment]
I'm able to duplicate, thanks for reporting, will have a fix pushed shortly.

**Comment by tritone11** [comment]
Great. Thanks for the work Aaron

**Comment by aaronjudd** [comment]
Fixed in `development` branch.

**Comment by tritone11** [comment]
I did a fresh install again and the issue persists identically. Does the normal install instruction connect to the development branch? Or to the master? (git clone https://github.com/reactioncommerce/reaction)

**Comment by tritone11** [comment]
I did a fresh install again and the issue persists identically. Does the normal install instruction connect to the development branch? Or to the master? (git clone https://github.com/reactioncommerce/reaction)

**Comment by tritone11** [comment]
I did a new fresh install from the development branch (-b development) and the issue persists. Now this is the console log:

M…r.m…e.errorClass {error: 404, reason: "Method not found", details: undefined, message: "Method not found [404]", errorType: "Meteor.Error"}
details: undefined
error: 404errorType: "Meteor.Error"
message: "Method not found [404]"
reason: "Method not found"
stack: (...)
get stack: ()
set stack: ()
__proto__: _.extend._inherits.Middleclone: ()constructor: (/*arguments*/)__proto__: DefineError.aV

It actually let me to change the options of the example products, but not to create new ones or to create options for new products.

**Comment by aaronjudd** [comment]
I'm not able to duplicate now, tested adding to variants, child variants to both new and existing product.

**Comment by aaronjudd** [comment]
Note:  It's the `development` branch of `reaction-core` you'll need to add in your `packages` folder (or use `PACKAGE_DIRS` env variable to clone to another location.

**Comment by tritone11** [comment]
I confirm that the issue is solved after cloning the reaction-core package from the branch development (-b development) inside /packages
